# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Allamal Quran' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Allamal Quran
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

  target 'Allamal QuranTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Allamal QuranUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
